-- Phase 8 — per-tenant WHS kinds taxonomy.
--
-- Creates whs_kinds inside the active per-tenant schema (search_path is set
-- to "tenant_<id>", public by per-tenant-migrate.ts) and seeds the four
-- system kinds that ship with every workspace.
--
-- The seed INSERT relies on app.tenant_id being set by the runner so that
-- current_setting() returns this tenant's UUID for the tracey_tenant_id
-- column. ON CONFLICT DO NOTHING keeps the migration idempotent if the
-- table is recreated for any reason.

CREATE TABLE IF NOT EXISTS whs_kinds (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL,
  label text NOT NULL,
  category text NOT NULL,
  is_system boolean NOT NULL DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  tracey_tenant_id text NOT NULL,
  CONSTRAINT whs_kinds_category_chk CHECK (category IN ('expiry', 'incident'))
);

CREATE UNIQUE INDEX IF NOT EXISTS ix_whs_kinds_tenant_slug
  ON whs_kinds (tracey_tenant_id, slug);
CREATE UNIQUE INDEX IF NOT EXISTS ix_whs_kinds_tenant_label
  ON whs_kinds (tracey_tenant_id, label);

ALTER TABLE whs_kinds ENABLE ROW LEVEL SECURITY;
ALTER TABLE whs_kinds FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS tenant_isolation ON whs_kinds;
CREATE POLICY tenant_isolation ON whs_kinds
  USING (tracey_tenant_id = current_setting('app.tenant_id', true))
  WITH CHECK (tracey_tenant_id = current_setting('app.tenant_id', true));

INSERT INTO whs_kinds (slug, label, category, is_system, tracey_tenant_id) VALUES
  ('high_risk_licence', 'High-risk licence',     'expiry',   true, current_setting('app.tenant_id', true)),
  ('fire_warden',       'Fire warden',           'expiry',   true, current_setting('app.tenant_id', true)),
  ('first_aider',       'First aider',           'expiry',   true, current_setting('app.tenant_id', true)),
  ('incident',          'Incident',              'incident', true, current_setting('app.tenant_id', true))
ON CONFLICT (tracey_tenant_id, slug) DO NOTHING;
