-- Add cancellation tracking columns to app.tenants so the dashboard can
-- distinguish "active, but cancellation scheduled" from "fully canceled" and
-- the billing gate can record when the cancellation took effect.
--
-- These columns are also generated by Drizzle (migrations/0004_brown_wasp.sql)
-- but this manual SQL is what gets run on Render via the External psql command
-- (see reference_render_db memory) — paste-and-run pattern, parameter-free.
--
-- Idempotent: ADD COLUMN IF NOT EXISTS, so re-running is a no-op.
--
-- ─── HOW TO RUN ──────────────────────────────────────────────────────
--
-- Local:
--   psql "postgres://root:root@localhost:5432/lms_dev" \
--        -f packages/db/migrations/manual/0007_cancel_at_period_end.sql
--
-- Render (lms-db):
--   1) Render dashboard → lms-db → Connect → External psql command.
--   2) Paste the two ALTER TABLE statements below into the prompt.
--   3) Run the (commented) verification SELECT to confirm.

ALTER TABLE app.tenants
  ADD COLUMN IF NOT EXISTS cancel_at_period_end boolean NOT NULL DEFAULT false;

ALTER TABLE app.tenants
  ADD COLUMN IF NOT EXISTS canceled_at timestamptz;

-- Verify after running:
-- SELECT id, name, status, cancel_at_period_end, canceled_at, current_period_end
--   FROM app.tenants
--  ORDER BY created_at DESC;
